[node]
data_dir = "C:\\Users\\Kevan\\popeye,mars,tar,tev\\scripts\\..\\data\\testnet\\node-a"
log_level = "debug"

[network]
listen_port = 30300
max_peers = 50
enable_discovery = true
bootstrap_peers = ["/ip4/127.0.0.1/tcp/30300"]

[runtime]
chain_id = "unykorn-testnet-aurora"
producer_enabled = true
producer_key = "48cd68735df686629c1737be57224217113886f68c37b77826a4552485458925"

[consensus]
propose_timeout = 3000
prevote_timeout = 2000
commit_timeout = 2000
timeout_delta = 500
max_rounds = 10
