[node]
data_dir = "C:\\Users\\Kevan\\popeye,mars,tar,tev\\scripts\\..\\data\\testnet\\node-c"
log_level = "debug"

[network]
listen_port = 30302
max_peers = 50
enable_discovery = true
bootstrap_peers = ["/ip4/127.0.0.1/tcp/30300"]

[runtime]
chain_id = "unykorn-testnet-aurora"
producer_enabled = true
producer_key = "1245789632587412589632587412589632587412589632587412589632587412"

[consensus]
propose_timeout = 3000
prevote_timeout = 2000
commit_timeout = 2000
timeout_delta = 500
max_rounds = 10
